### ISSUE TITLE
cordova build android failed

### ISSUE THREAD

**Issue by bertrandmd** [janeasystems/nodejs-mobile#10]
* **Version**: v5.12.0
* **Platform**: macOS 10.11.6
* **Subsystem**:

Hello, I'm trying to use your plugin with cordova and android.
when I add the plugin, next build command failed with this message :

```
A problem occurred configuring root project 'android'.
> NDK not configured.
  Download it with SDK manager.)
```

if I remove the plugin, I can normally run the build command

In Android Studio I have Android platforms 5.0 to 7.0 installed
SDK Tools version 26.1.1 installed
NDK 15.2.4203891 installed

Do you know if a particular configuration is needed for cordova/android ?

Thanks !

**Comment by enricogior** [comment]
Hi @bertrandmd,
thank you for opening the issue.
This is a known issue, we will update the README soon, and we will also fix it as soon as possible.
As a workaround for now, after the missing NDK error, import `platforms/android/` in Android Studio as a `gradle` project, that should take care of fixing the missing dependencies/pre-requisites and allow you to run `cordova android build --device` successfully.
Let me know it that helped.
Thanks.

**Comment by bertrandmd** [comment]
Hi @enricogior, 
thanks for fast reply.

I just opened `platforms/android/` in Android Studio.
then now I have 
```
Error: Could not find gradle wrapper within Android SDK. Might need to update your Android SDK.
```
:(

**Comment by enricogior** [comment]
@bertrandmd
that is an issue with your current Android SDK configuration.
First make sure you have all the Cordova requirements for you platform:
https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html

If that is not solving your issue, try searching for `Could not find gradle wrapper within Android SDK` on google, you will find instructions on how to update your SDK using the Android Studio's SDK Manager.
Make also sure you have the Android NDK installed.

**Comment by bertrandmd** [comment]
@enricogior,
thanks a lot for your help.

I fix the issue with this update :
`cordova platform update android@6.2.1`

It's works !

**Comment by enricogior** [comment]
@bertrandmd,
you're welcome!
We will include the 6.2.1 requirement in the plugin settings.
Let's keep the issue open until we push the update.
Thanks for the feedback!

**Comment by ehhthing** [comment]
Hi, I was able to fix this issue by adding "ANDROID_NDK_HOME" in to my environment variables with the value "C:\Android\android-sdk\ndk-bundle" (Or wherever your ndk is located)

**Comment by bil-ash** [comment]
The problem still persists on my windows 10 PC after trying all the above workarounds. Also it seems the iOS portion of the plugin is paid more attention then the Android counterpart.

**Comment by jaimecbernardo** [comment]
Hi, @bil-ash .

You could try opening your app's `platforms\android\` path in Android Studio to see if Gradle detects any missing dependencies in "Event Log". One of the side effects of this is that Android Studio creates a `platforms\android\local.properties` file with the `ndk.dir` and `sdk.dir` values for your machine.

I hope this is helpful.

**Comment by bil-ash** [comment]
@bil-ash I found out the solution. It was not a problem with the plugin,but with my setup. A few weeks before using the plugin I had switched from 64-bit to 32- bit jdk for something else and that was causing the problem. This is because the cmake of android ndk does not work with 32-bit jdk on windows(any version).
Thanks janeasystems for the plugin

**Comment by sureshkumar-s89** [comment]
Hi,

I'm beginner to cordova, I have created cordova application as instructed [here](https://www.npmjs.com/package/nodejs-mobile-cordova) and I'm able to run the application successfully on Android emulator from windows command line.

Platform: Windows 10 64-bit
Cordova version: 7.0.1
Java version: "1.8.0_144" (64-Bit Server VM)
Android platform (in config.xml): "android" spec="^6.2.3"
Android Emulator details: 

- Name: Nexus_5X_API_25
- CPU/ABI: Google Play Intel Atom (x86)
- Target: google_apis_playstore [Google Play] (API level 25)

In index.js file I changed to show alert box instead of console.log. First I get "NodeJs Engine Started" alert message but in next alert I did not get "[cordova] received: Replying to this message: Hello from Cordova!", instead I get only "[cordova] received:".

Am I missing anything?

**Comment by jaimecbernardo** [comment]
Hi @sureshkumar-s89 ,
Thank you for the question.

Cordova seems to have some issues with comma-separated variable number of arguments for calls to `console.log` and perhaps this also affects calls to `alert`.

If your line is `alert("[cordova] received:", msg);`, would you mind trying to change it to `alert("[cordova] received: " + msg);` ? (Just swap the `,` for a `+`)

Please let us know if this was the issue.

**Comment by sureshkumar-s89** [comment]
Hi @jaimecbernardo,
Thank you for the quick response.

As you suggested, I replaced `,` with `+` and now I'm getting the response ("[cordova] received: Replying to this message: Hello from Cordova!") from nodejs engine.

Thanks again, and I will try it with my requirement.

**Comment by jaimecbernardo** [comment]
This issue has been open for a while and was about help getting started, so I'm closing it now.
