### ISSUE TITLE
Unsupported opperating system for nodejs-mobile native builds: Windows 10

### ISSUE THREAD

**Issue by ghost** [janeasystems/nodejs-mobile#110]
Node Version: 8.9.4
Platform: windows 10 64 bit

```
The error regards to build native modules on windows. Is it not supported?
```

I use this platform:
cordova cli: 7.0.0
android platform: 6.3.0
mobile-nodejs-cordova: 0.2.0

To skip the error I created a ```www/NODEJS_MOBILE_BUILD_NATIVE_MODULES_VALUE.txt``` with ```0``` value

**Comment by jaimecbernardo** [comment]
Hi @amanganiello90 ,
Building native modules for mobile is not supported on Windows yet. It's supported on Linux and MacOS, as mentioned here: https://github.com/janeasystems/nodejs-mobile-cordova/tree/79092d967a1c6b35abd0f7b2f1dd436582f439ec#native-modules

There have been reports of of users being able to use "Windows subsystem for Linux" in order to build the native modules: https://github.com/janeasystems/nodejs-mobile/issues/4#issuecomment-377177162

**Comment by ghost** [comment]
Thanks, I read that. I hope that in the future there will be that support.
