### ISSUE TITLE
Nodemon throws error: 'cannot find module rn-bridge' in React Native?

### ISSUE THREAD

**Issue by abrarum** [janeasystems/nodejs-mobile#113]
Version: output of `react-native run-android`
Platform: output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)
Subsystem: if known, please specify affected core module name

* **Version**: Latest
* **Platform**: Windows / React-Native

Apps can be debug without refreshing by Nodemon. I've used it in web. Upon installing and debugging, Node.js starts and there is no way to stop the nodejs thread. So, the code that has been changed doesn't reflect immediately hence it needs a long process of compile in order to start Node and debug again.

**Comment by jaimecbernardo** [comment]
Hi @abrarum ,

That is the expected behavior, as described in the README.md : https://github.com/janeasystems/nodejs-mobile-react-native/tree/187551aeabb71eb5964d19b496d219c6598f88fd#react-native-application
> Attention: The Node.js project runs on a dedicated thread and as a singleton, so only the first `nodejs.start()` command will make any effect, as further calls will not start new threads. This means that if you use react-native's hotreload functionality you won't see any changes in the Node.js project.

Regarding the error: `cannot find module rn-bridge`:
`rn-bridge` is a native module that is loaded with the application, that contains mobile-specific native code. I'm not familiar with nodemon, but this might be a reason why it is not being found by nodemon?

**Comment by abrarum** [comment]
This might be the reason. So isn't there any method for stopping nodejs in your api?

**Comment by jaimecbernardo** [comment]
There isn't any method for stopping the nodejs runtime in the API.
The scenario implemented in the React-Native is through calling `node::Start`, which sets the libuv loop and expects to be the single instance of node running in the process, similar to running node as a standalone application.
