### ISSUE TITLE
Cordova Plugin not working as expected with older Android versions (<=23)

### ISSUE THREAD

**Issue by stoically** [janeasystems/nodejs-mobile#119]
```
$ node -v
v8.11.3

$ nvm --version
0.26.1

$ uname -a
Linux user@pc 4.4.0-134-generic #160-Ubuntu SMP x86_64 GNU/Linux
```

* package.json dependency **versions**: 
```  "dependencies": {
    "cordova-android": "^6.3.0",
    "cordova-plugin-whitelist": "^1.3.3",
    "nodejs-mobile-cordova": "^0.2.1"
  }
```
* **Platform**: Ubuntu 16.04, Linux x86_64
* **Subsystem**: chakracore

**Steps to reproduce**
Install an emulator with Android version 6.x (API level 23)
Follow the steps to run the cordova plugin
Watch how the console logs a failure because of `...` usage

Not sure if you plan to support Android 6.x - but if you plan to do so, it's easy to use `Object.assign` instead of the spread operator. I could provide a PR.

**Comment by jaimecbernardo** [comment]
Hi @stoically ,

This issue is similar to: https://github.com/janeasystems/nodejs-mobile/issues/105#issuecomment-412549133

It seems to be occuring in devices which haven't received WebView updates in many years and is not connected to the Android version. The Android emulator for 6.x seems to have an old WebView as well and that's why it also happens there.

A "babel"-ified version of the plugin was pushed to a branch for these cases, which could help solve the problem : https://github.com/janeasystems/nodejs-mobile-cordova/tree/staging-babel-UI-runtime

According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility , `Object.assign` is not supported on Android WebViews.

**Comment by stoically** [comment]
Thanks for the fast reply, can confirm that it works with the staging-babel-UI-runtime branch!
