### ISSUE TITLE
Add iOS Simulator support

### ISSUE THREAD

**Issue by lukaskollmer** [janeasystems/nodejs-mobile#12]
I don't know how difficult this would be, but IMO `libnode.framework` should contain slices for both arm46 and i386 to support runing on both actual devices and the iOS simulator.

The main reason for this is of course allowing development and testing in the simulator. This would also allow apps built against libnode to run on CI tools like travis or circle since they run unit tests in the simulator.

Do you think this is possible / is this something you're interested in supporting?

**Comment by jaimecbernardo** [comment]
Hi @lukaskollmer,

Thanks for the issue.
Supporting a x86_64 slice for the simulator is a high priority item in our roadmap.

In terms of CI, our current plan is to run it on actual devices, since a successful run on the Simulator doesn't guarantee a 100% pass on physical devices. One example of this is that the simulator lets you start new child processes, while this is forbidden in physical devices.

**Comment by lukaskollmer** [comment]
Good to hear! Do you have an ETA on this?

**Comment by jaimecbernardo** [comment]
We expect to make it available on the next release, which should be out in the next couple of weeks.

**Comment by jaimecbernardo** [comment]
The iOS simulator support has been added to the `mobile-master` branch, so it will be out with the next release.
The universal framework can be built from that branch, if you need it in the meanwhile, as the build instructions have been updated as well. Let us know if you run into any problem.
I'm closing this issue.
