### ISSUE TITLE
App Store Submission

### ISSUE THREAD

**Issue by ccorcos** [janeasystems/nodejs-mobile#131]
Has anyone gotten App Store approval with this package? 
https://github.com/janeasystems/nodejs-mobile-cordova

**Comment by ccorcos** [comment]
> 3.3.2 An Application may not download or install executable code. Interpreted code may only be used in an Application if all scripts, code and interpreters are packaged in the Application and not downloaded. The only exception to the foregoing is scripts and code downloaded and run by Apple’s built-in WebKit framework or JavascriptCore, provided that such scripts and code do not change the primary purpose of the Application by providing features or functionality that are inconsistent with the intended and advertised purpose of the Application as submitted to the App Store.

**Comment by ccorcos** [comment]
Looks like it works if we don't change the code...

**Comment by mohlsen** [comment]
I saw Janea retweet this, so I am pretty sure there is at least one app out there:  https://twitter.com/JaneaSystems/status/1044617929550106625

In a Cordova app using *nodejs-mobile-cordova*, there are real two area of concern.  

1. The HTML/JS/CSS code used in your Cordova app is interpreted by WebKit framework or JavascriptCore (via WKWebView or UIWebView - depending on your Cordova configuration). This is proven should noybe a concern, if this was an issue, Cordova would not be a viable framework. You can even download your code on the fly with frameworks such as [CodePush](https://github.com/Microsoft/cordova-plugin-code-push) based on the exception mentioned in 3.3.2.
2. The JS that is run in Node.js by *nodejs-mobile-cordova*.  Since that code would be bundled in the app as well, it is ok.  Also of note, *nodejs-mobile-cordova* does not use WebKit framework or JavascriptCore, but uses [Node.js on ChakraCore](https://github.com/nodejs/node-chakracore) configured to use an interperiter instead of a JIT.  This choice was made becasue propper Node.js with v8 would be using JIT, this violating the following:
    >  Interpreted code may only be used in an Application if all scripts, code and interpreters are packaged in the Application and not downloaded

Hope this helps explain it.

**Comment by jaimecbernardo** [comment]
Hi @ccorcos ,

We've had users report getting their Apps that use nodejs-mobile in the App Store.
@mohlsen comment explains it well. Thank you!

**Comment by ccorcos** [comment]
Thanks!
