### ISSUE TITLE
leveldown@4.0.1 and react-native@0.59.4 crash with __aeabi_memcpy missing

### ISSUE THREAD

**Issue by staltz** [janeasystems/nodejs-mobile#182]
This issue is fully described in a repository I made with code samples and reproduction instructions: https://github.com/staltz/nodejs-mobile-issue182

* **Version**: nodejs-mobile-react-native 0.4.0

**Comment by staltz** [comment]
Could be related to this: https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md#target-api-set-higher-than-device-api (Target API set higher than Device API)

**Comment by jaimecbernardo** [comment]
Hi @staltz,

Thank you for reporting this issue!

Unfortunately I don't have any readily available Marshmallow device to give this issue a test.
From the link you posted the issue is probably that we using the target SDK level to compile the native modules instead of the minimum sdk level:

https://github.com/janeasystems/nodejs-mobile-react-native/blob/022c47e67f298d89170aea8e7b5e31103f433ebb/android/build.gradle#L339

One of the ways to give this a test would be to replace the `"--platform=android-${_nodeTargetSdkVersion}"` part with `"--platform=android-21"`, to use the API level 21 from your sample:
https://github.com/staltz/nodejs-mobile-issue182/blob/001441cded17571d698cc24f4f776a930cd27e88/reactnative059/android/build.gradle#L6

Could you please give it a try and let me know?
If this works, changing the gradle file to use the minimum level instead of the target level is straightforward.

**Comment by staltz** [comment]
I think I managed to solve this by setting `targetSdkVersion 23` in `android/app/build.gradle`. Still testing, but so far no crashes.

Thanks @jaimecbernardo
