### ISSUE TITLE
Apple Review rejected because of non-public API usage

### ISSUE THREAD

**Issue by dungntm58** [janeasystems/nodejs-mobile#185]
* **Version**: v0.4.0
* **Platform**: iOS

I've just used the latest version of nodejs-mobile-react-native to release my React Native app. A few days ago, I got an email from Apple. It said that my app violated one of the guidelines.

> Dear Developer,
>
> We identified one or more issues with a recent delivery for your app, "". Please correct the following issues, then upload again.
>
> * **Non-public API usage:**
>
> The app references non-public symbols in Frameworks/NodeMobile.framework/NodeMobile: _getcontext, _makecontext, _setcontext
If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.
>
> If you think this message was sent in error and that you have only used Apple-published APIs in accordance with the guidelines, send the app's nine-digit Apple ID, along with detailed information about why you believe the above APIs were incorrectly flagged, to appreview@apple.com. For further information, visit the Technical Support Information page.

I got no trouble to distribute my app with v0.3.0. The only reason I have to upgrade to v0.4.0 is a crash on iPhone XS. What should I do to resolve this issue?

**Comment by jaimecbernardo** [comment]
Hi @dungntm58 ,

Thank you for reporting this.
It looks like these symbols are being referenced from openssl inside node, in these files:

https://github.com/janeasystems/nodejs-mobile/blob/5513cc885562983d8ed5c042e99e17948c3fa0d2/deps/openssl/openssl/crypto/async/arch/async_posix.c

and

https://github.com/janeasystems/nodejs-mobile/blob/5513cc885562983d8ed5c042e99e17948c3fa0d2/deps/openssl/openssl/crypto/async/arch/async_posix.h

I'll test some configurations in order to get binaries without the symbols for iOS.

**Comment by jaimecbernardo** [comment]
Hi @dungntm58 ,

I've built a version of the library without reference to the private symbols mentioned in the App Store message.
The library was built from this fork branch: https://github.com/jaimecbernardo/nodejs-mobile/tree/openssl-remove-context-symbols
The resulting iOS binary was added to `nodejs-mobile-react-native` in this fork branch: https://github.com/jaimecbernardo/nodejs-mobile-react-native/tree/remove-openssl-context-symbols-ios

Would you mind giving it a try? For doing so, run these lines in your project in order to use the specific branch I've referenced.
```
react-native unlink nodejs-mobile-react-native
npm uninstall nodejs-mobile-react-native
npm install https://github.com/jaimecbernardo/nodejs-mobile-react-native.git#remove-openssl-context-symbols-ios
react-native link nodejs-mobile-react-native
```

The binary contained in the version doesn't contain the mentioned symbols. This was verified by running:
```
nm -g NodeMobile.framework/NodeMobile | grep -e setcontext -e getcontext -e makecontext
```

Please let us know if you're willing to try submitting a version of your Application with this binary, and let us know of the results you get, so these changes can be applied to a new release of the plugin.
Thank you in advance.

**Comment by dungntm58** [comment]
Thank you so much, I'll try and give you the result.

**Comment by dungntm58** [comment]
Hi @jaimecbernardo , I released my app successfully. So I will close the topic.

**Comment by jaimecbernardo** [comment]
Hi @dungntm58 ,
Thank you for letting us know.
The change will be applied to the official releases.

**Comment by jaimecbernardo** [comment]
There's been a release with the fix for this issue:
https://www.npmjs.com/package/nodejs-mobile-react-native/v/0.4.1

**Comment by cyberiums** [comment]
Is this fix applicable for IONIC/Cordova?

**Comment by jaimecbernardo** [comment]
Hi @cyberiums ,
Yes, it was applied to Cordova in: https://www.npmjs.com/package/nodejs-mobile-cordova/v/0.3.1
