### ISSUE TITLE
require('os').cpus().length fails on iOS device

### ISSUE THREAD

**Issue by IMcD23** [janeasystems/nodejs-mobile#20]
Many node libraries get the number of CPUs on a host by using the node 'os' module. This works fine in the simulator, but cpus() returns undefined on device.

This is because the `sysctlbyname("hw.cpufrequency")` call fails on iOS devices, since they don't have a property by that name. It's successful on the iOS Simulator, since that syscall is passed to the Mac it is run on.

Would it be reasonable to gracefully handle this error and continue, instead of returning undefined? It's still possible to get the other CPU info, aside from the CPU frequency.

See `deps/uv/src/unix/darwin.c`:`uv_cpu_info` for where this is implemented.

**Comment by jaimecbernardo** [comment]
Hi @IMcD23 , Thank you for the issue.
I've added a PR for `os.cpus` to have 0 as the `speed` value on iOS. As a basis for that, I took the `times.nice` behavior on Windows, which is filled with 0 since it's unavailable. Source: https://nodejs.org/docs/latest-v8.x/api/os.html#os_os_cpus

PR: https://github.com/janeasystems/nodejs-mobile/pull/36

**Comment by jaimecbernardo** [comment]
Fixed in https://github.com/janeasystems/nodejs-mobile/commit/12747ef24b8cdad82b4dd5f9120386e012920243
