### ISSUE TITLE
building release for ios - Release/.node' is not permitted.

### ISSUE THREAD

**Issue by export-mike** [janeasystems/nodejs-mobile#206]
node -v 
v10.15.1

building ios: creates output error on upload to testflight.

```bash
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'Test.app/nodejs-project/node_modules/fsevents/build/Release/.node' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
ERROR ITMS-90189: "Redundant Binary Upload. You've already uploaded a build with build number '3' for version number '4.5.0'. Make sure you increment the build string before you upload your app to App Store Connect. Learn more in Xcode Help (http://help.apple.com/xcode/mac/current/#/devba7f53ad4)."
Return status of iTunes Transporter was 1: ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'Test.app/nodejs-project/node_modules/fsevents/build/Release/.node' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app b\nERROR ITMS-90189: "Redundant Binary Upload. You've already uploaded a build with build number '3' for version number '4.5.0'. Make sure you increment the build string before you upload your app to App Store Connect. Learn more in Xcode Help (http://help.apple.com/xcode/mac/current/#/devba7f53ad4)."
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
```

I'm using react-native nodejs-mobile.

any help on getting a release build for ios would be helpful

thanks

**Comment by jaimecbernardo** [comment]
Hi @export-mike ,

Looks like this is happening due to the `fsevents` module having a `.node` file, which contains native code. react-native has some code to rebuild the native modules and should delete the ones that were created as part of the previous `npm install`.

This is done as part of a custom build script in the Xcode project that is added when the react-native links `nodejs-mobile-react-native`:
https://github.com/JaneaSystems/nodejs-mobile-react-native/blob/49c069539db138688a9e44c44180bb0c3335537c/scripts/module-postlink.js#L217-L226

In your case, this file is not being deleted. Please try to delete the faulty file as part of the build process too, by editing the `Build NodeJS Mobile Native Modules` Custom Build Step in the xcode project of your Application and let us know if this solved the issue.

**Comment by export-mike** [comment]
hi yes this file was being added even though it was from a devDependency babel cli. 
strange anyway. I've since updated it and its now working
