### ISSUE TITLE
iOS Node Server down after lock/unlock device

### ISSUE THREAD

**Issue by asielgil88** [janeasystems/nodejs-mobile#210]
* **Project**:
* **Version**: pod 'NodeMobile', :git => 'https://github.com/janeasystems/nodejs-mobile.git'
* **Mobile device**: IPad 5 genration
* **Mobile OS and version**: iOS
* **Development Node.js**:
* **Development platform**:

After device is lock, and then unlock Node server stop working 
all responses for client came as 

```NSLocalizedDescription=Could not connect to the server., NSErrorFailingURLStringKey=http://localhost:6000/getTransactions, NSErrorFailingURLKey=http://localhost:6000/getTransactions, _kCFStreamErrorDomainKey=1} [-1004]```

**Comment by jaimecbernardo** [comment]
Hi,

iOS will close the sockets for Applications in the background:
https://github.com/JaneaSystems/nodejs-mobile/issues/62#issuecomment-380109120

Listening to socket / server errors in the node runtime and re-opening them could be helpful for dealing with this.

**Comment by asielgil88** [comment]
Hi thanks for your response, in this thread(https://github.com/robbiehanson/CocoaHTTPServer/issues/10), they mentioned this as the correct behavior

-on applicationDidEnterBackground: I stop the HTTP server
-on applicationWillEnterForeground: I start the HTTP server

did you have any code example how to achieve that, i haven't been able to find how stop and resume node server in iOS

using the nodejs mobile example the NodeRunner only has **node_start** function

note: I'm not running a react-native my app is native iOS

**Comment by jaimecbernardo** [comment]
Hi @asielgil88 ,

The cordova and react-native plugins have communication channels in order to do this.
How to communicate with the node instance depends on your Application specifics when using nodejs-mobile as a native library.

Building a bridge like the one in the plugins would be one way of achieving this. Links to some code parts to help in this can be found in: https://github.com/JaneaSystems/nodejs-mobile/issues/61#issuecomment-378531155

A simpler approach was taken in an older sample where pipes were used for communicating these control commands. Here are some parts of that code:
- https://github.com/JaneaSystems/node-mobile-react-demo/blob/24eeaef8aabbb1c760384b758c9d5e820118b7d5/ios/PouchAlbum/AppDelegate.m#L40-L47
- https://github.com/JaneaSystems/node-mobile-react-demo/blob/24eeaef8aabbb1c760384b758c9d5e820118b7d5/ios/PouchAlbum/NodeRunner.mm#L99-L102
- https://github.com/JaneaSystems/node-mobile-react-demo/blob/24eeaef8aabbb1c760384b758c9d5e820118b7d5/nodeproj/main.js#L188-L217

In an alternative strategy, the server or socket object used in the Node.js should thrown an 'error' event when the app resumes in case the connection was closed while the App was in the background. Have you tried handling this event and restarting the server? https://nodejs.org/dist/latest-v10.x/docs/api/net.html#net_event_error

**Comment by asielgil88** [comment]
Thanks this was really helpful

**Comment by export-mike** [comment]
any guidance on doing this with the latest version? I'm using react-native too
