### ISSUE TITLE
Unable to resolve module `react-native/Libraries/vendor/emitter/EventEmitter` (RN<0.48)

### ISSUE THREAD

**Issue by nomoreboredom** [janeasystems/nodejs-mobile#23]
* **Version**: v8.9.0
* **Platform**: 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
* **Subsystem**: EventEmitter

First of all thanks for all the efforts to bring node.js to mobile!!

After npm install and react-native link command, when I try to run the app I see this error. I am using ios with the simulator device, with the RN version 0.47.2, if it makes a difference.

Any idea what may be causing this, I have tried this regular watchman, packager and npm clear commands. 
Thanks.

**Comment by jaimecbernardo** [comment]
Thanks for the issue, @nomoreboredom 

I believe the problem is on `React Native`'s EventEmitter location, which changed in version 0.48 (the version we used to test and develop the plugin). https://github.com/janeasystems/nodejs-mobile-react-native/blob/bbf5c46566ab3b1789bfe633453f9d792f51f858/index.js#L3

This is the commit that changed to React Native that changed the location: https://github.com/facebook/react-native/commit/365aea3415fdf3e16a6643862a0bfacf87b2f1d1

So, I'd advise either using RN version >= 0.48 or trying to change the https://github.com/janeasystems/nodejs-mobile-react-native/blob/bbf5c46566ab3b1789bfe633453f9d792f51f858/index.js#L3 line in your `node_modules/nodejs-mobile-react-native/index.js` from `var EventEmitter = require('react-native/Libraries/vendor/emitter/EventEmitter');` to `var EventEmitter = require('react-native/Libraries/EventEmitter/EventEmitter');`

Hope this was helpful. Please let us know of any developments.
I'm leaving this issue open to track it and changing the title accordingly.

**Comment by nomoreboredom** [comment]
Thank you for your fast response Jaime, everything is good now :)
