### ISSUE TITLE
Implement spawn, child process (not supported)

### ISSUE THREAD

**Issue by rlaurente** [janeasystems/nodejs-mobile#25]
Good Job on this plugin!

I'm trying to spawn multiple local script. I tried it but it didnt fire the script, I guess node is not recognize in mobile devices. Do you have idea how can I implement child process ? 

Thanks

**Comment by jaimecbernardo** [comment]
Thank you for the issue, @rlaurente 

Spawning new processes is not allowed in iOS applications (enforced by iOS), due to security reasons, so we're not trying to support this functionality for neither platform, to keep the supported features similar between the mobile platforms.

On Android, you should be able to create child processes, even if it's not supported by the project.

I hope this was helpful.

**Comment by jaimecbernardo** [comment]
This issue refers to a feature which isn't planned to be supported and will probably be impossible to support, so I changed the title and am closing it.

**Comment by herme5** [comment]
Hi,
I want to know if there is a workaround to launch two Node instances on iOS devices ? Almost every attempts to do this at the javascript side (cluster, worker_threads, child_process) led me to the same error :

`Error: spawn EPERM at ChildProcess.prototype.spawn (internal/child_process.js:358:5)`

I understand iOS does not let subprocesses to be spawned but I am missing something. Sorry if my questions may seem quite naive: 
- is the first instance a subprocess ? 
- is there any virtualization ?
- if so, why cannot `node_start()` be called twice on two separate ios native threads ? Isn't there a way to create and recreate virtual spaces so that the instances does not share memory ?

Thanks !

**Comment by jaimecbernardo** [comment]
Hi @herme5 ,

Regarding your questions:
- The first instance is a thread.
- What do you mean by virtualization in this case?
- The node runtime when used through `node_start()` uses global variables and asserts to verify that it's not running in the same process. Perhaps some different start instructions to `node_init()` would support your scenario.

For more discussion on this topic, this has also been discussed in other issues, like:
https://github.com/janeasystems/nodejs-mobile/issues/66
https://github.com/janeasystems/nodejs-mobile/issues/98
https://github.com/janeasystems/nodejs-mobile/issues/166

**Comment by herme5** [comment]
Hi @jaimecbernardo , thanks for the reply.

Maybe I went too far with virtualization, I got lost into threads and processes. I just wanted to know if there is a thing that encapsulate node so that it does not conflicts threads, memory etc... but it is not relevant actually.

I think things are a bit more clear in my mind. Reading #98 I decided to do it on the node side: encapsulating js scripts so that each one exports a `init` function, and then requiring them and call all the `.init()` in a `main.js`. Works fine !
