### ISSUE TITLE
iTunes submission errors

### ISSUE THREAD

**Issue by bushev** [janeasystems/nodejs-mobile#30]
* **Version**: v8.9.1
* **Platform**: High Sierra

Hello guys! Thank you for the nice library!

I'm trying to submit the app to AppStore, but it fails with errors (see screenshot). I use React Native plugin (v0.1.2).

![image](https://user-images.githubusercontent.com/7535766/34464950-39c23292-eea8-11e7-9b89-b42ad60affe5.png)

**Comment by jaimecbernardo** [comment]
Hi @bushev,
Thank you for the issue. 
This seems to be caused due to the core library inside the react-native plugin having both `arm64` (for running on devices) and `x86_64` (for running on the simulator) architectures.
The app store doesn't allow submitting applications with x86_64 slices.

The [core library release](https://github.com/janeasystems/nodejs-mobile/releases/tag/nodejs-mobile-v0.1.3) for iOS has two versions inside, `Release-iphoneos` and `Release-universal`. Could you please try replacing the `node_modules/nodejs-mobile-react-native/ios/libnode.framework` inside your react-native project with the `Release-iphoneos/libnode.framework` from the release? That one only has the arm64 slices for devices.

After testing if this was the issue but you still want to keep the Universal framework for debugging in the simulator, you could add a build script to strip the unwanted architectures while the application is building, like in this SO question: https://stackoverflow.com/a/41416964

I hope this is helpful. Please let us know of any developments.

**Comment by bushev** [comment]
@jaimecbernardo Hi! It helps, thank you!
