### ISSUE TITLE
Crashed in result = JX_LoopOnce();

### ISSUE THREAD

**Issue by ilioner** [janeasystems/nodejs-mobile#38]
* **Version**:
* **Platform**:
* **Subsystem**:

**Comment by jaimecbernardo** [comment]
Hi @ilioner , thank you for the issue.

The issue you are reporting doesn't seem to be related to `nodejs-mobile`, as `JX_LoopOnce();` is not part of this project. From the function's name, you are probably trying to use `JXCore`: https://github.com/jxcore/jxcore 

I hope this was helpful.
I'm closing the issue, since it's not related to this project.
