### ISSUE TITLE
[bug] out of stack space

### ISSUE THREAD

**Issue by florianlenz** [janeasystems/nodejs-mobile#43]
* **Version**: 8.9.3
* **Platform**: 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
* **Subsystem**: react native 0.52.1

## Issue
I stress tested (was not on purpose) the react native bridge and got the following error: 
```
2018-02-05 13:26:50.736 [info][tid:com.facebook.react.JavaScript] Running application "libp2pReactNativeTest" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
2018-02-05 13:26:50.736070+0100 libp2pReactNativeTest[28659:4151294] Running application "libp2pReactNativeTest" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
Discovered: QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ
Discovered: QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z
Discovered: QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM
Discovered: QmSoLueR4xBeUbY9WZ9xGUUxunbKWcrNFTDAadQJmocnWm
Discovered: QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu
Discovered: QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64
Discovered: QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd
Discovered: QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3
Discovered: QmSoLju6m7xTh3DuokvT3886QRYqxAzb1kShaanJgW36yx
Connected to: QmSoLMeWqB7YGVLJN3pNLQpmmEk35v6wYtsMGLzSr5QBU3
undefined:1
undefined
^

Error: Out of stack space
```

## Reproduce
1. Get the repo from here: https://github.com/florianlenz/libp2ptest
2. Checkout this commit: 2d6dc4d48b09a8a5395a0d7db4b2c4ac5704760a (`git checkout 2d6dc4d48b09a8a5395a0d7db4b2c4ac5704760a`)
3. Install the dependencies 
4. Run the app in the ios simulator or device (since this program interact's with your network you need to allow it when running in the terminal). 

Cheers,
Florian

**Comment by florianlenz** [comment]
Ops, this also happen's when using e.g. console.log in the simulator. So it's not related to the react bridge.

**Comment by jaimecbernardo** [comment]
Hi @florianlenz 
I've been able to reproduce the error. Thank you for making the code available for production. We'll look into this.

**Comment by jaimecbernardo** [comment]
Hi @florianlenz , I've identified a potential source for this bug.

ChakraCore's Platform Adaptation Layer threads seem to expect to have at least 1MB of stack space available on iOS: https://github.com/janeasystems/nodejs-mobile/blob/12747ef24b8cdad82b4dd5f9120386e012920243/deps/chakrashim/core/pal/src/thread/pal_thread.cpp#L64

However, having 1MB of stack space is true only for the main iOS Application's thread. Secondary threads, which is the case for the thread node-mobile is running on, have a default size of 512KB, according to Apple's documentation: https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Multithreading/CreatingThreads/CreatingThreads.html#//apple_ref/doc/uid/10000057i-CH15-SW7

I've been able to eliminate the bug on the react-native side by forcing the thread to have 1MB of stack space instead of the default 512KB.
This can be done by adding the following line right before starting the nodejs-mobile thread:
```
    [nodejsThread setStackSize:1024*1024]; //This line
    [nodejsThread start];
```

Add that line here https://github.com/janeasystems/nodejs-mobile-react-native/blob/d478d029d76e7d1de8b52d1cd5c51f7d61067b31/ios/RNNodeJsMobile.m#L84 and here https://github.com/janeasystems/nodejs-mobile-react-native/blob/d478d029d76e7d1de8b52d1cd5c51f7d61067b31/ios/RNNodeJsMobile.m#L99

You should be able to edit this file inside the `react-native` project in `node_modules/nodejs-mobile-react-native/ios/RNNodeJsMobile.m` or in the iOS project open in Xcode in the Project's Explorer inside `Libraries/RNNodeJsMobile.xcodeproj/RNNodeJsMobile.m`.

I hope this workaround is helpful while we investigate this bug further.

**Comment by jaimecbernardo** [comment]
This issue has received a fix which is released for both plugins: https://github.com/janeasystems/nodejs-mobile-cordova/commit/7ac8dd9b01446d1bbfb2b76da8ecd3b7c502918a and https://github.com/janeasystems/nodejs-mobile-react-native/commit/940fcfe5f14baf9976d8714b3aa321fc094821b7

Closing this issue until there are news of the error reappearing.

**Comment by spentak** [comment]
Getting this issue on native iOS as well.

`npm install nem-library rxjs --save`

The nem-library package is what causes the issue.

Simply importing it: `var nem = require('nem-library');`
Throws the error:

```bash
fs.js:653
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
  ^

Error: Out of stack space
   at fs.openSync (fs.js:653:3)
   at fs.readFileSync (fs.js:554:3)
   at Module._extensions[.js] (module.js:634:3)
   at Module.prototype.load (module.js:545:3)
   at tryModuleLoad (module.js:508:5)
   at Module._load (module.js:500:3)
   at Module.prototype.require (module.js:568:3)
   at require (internal/module.js:11:7)
   at Anonymous function (/private/var/containers/Bundle/Application/C00B921C-A83F-4A6D-B8AB-1FF8715FE05B/native-xcode-node-folder.app/nodejs-project/node_modules/sshpk/lib/formats/pem.js:9:1)
   at Module.prototype._compile (module.js:624:5)
```
It is coming from a cryptography module: `sshpk`
`node_modules/sshpk/lib/formats/pem.js:9:1`

**Comment by spentak** [comment]
Okay this can be fixed by increasing the stack size like so:

```
-(void)launchNode {
    NSString* srcPath = [[NSBundle mainBundle] pathForResource:@"nodejs-project/main.js" ofType:@""];
    NSArray* nodeArguments = [NSArray arrayWithObjects:@"node", srcPath, nil];
    [NodeRunner startEngineWithArguments:nodeArguments];
}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    
    NSThread *t = [AppDelegate createThreadWithTarget:self selector:@selector(launchNode) object:nil stackSize:1024*1024];
    [t start];
    return YES;
}
```

**Comment by jaimecbernardo** [comment]
@spentak , Thank you for the report. The samples / getting started docs will be updated to include the detail.
