### ISSUE TITLE
Have any plan to support iOS 8.4.1?

### ISSUE THREAD

**Issue by aniude** [janeasystems/nodejs-mobile#46]
When I run the XCode to build the target into my iPad. And the XCode waninng:

>  iOS 8.4.1 doesn’t match NodeMobile.framework’s iOS 9.0 deployment target. Upgrade xxxx iPad’s iOS version or lower NodeMobile.framework’s deployment target.

**Comment by jaimecbernardo** [comment]
Hi @aniude , thank you for the question.
The plan is for supporting `iOS 11.0` or greater, since we're supporting 64-bit binaries only.

So, the short answer is no: we're not planning to support 8.4.1. However, we've accepted a PR to lower the version in the framework project to ` iOS 9.0`: https://github.com/janeasystems/nodejs-mobile/pull/18
You could try rebuilding the framework with a lower `iOS` target by looking into the necessary changes.

I hope this is helpful.

**Comment by jaimecbernardo** [comment]
There is no plan to support this version of iOS, so I'm closing this issue. If a Pull Request comes to support it, we'll evaluate it at the time. Thank you.
