### ISSUE TITLE
How to use/install 'express' module?

### ISSUE THREAD

**Issue by DeepakArora76** [janeasystems/nodejs-mobile#49]
Thanks a lot for making NodeJs possible to run on Android and iOS platforms.

My question is not related to the Core, but in general NPM package, especially **express**.  I want to use this package. For some reason, I am unable to have an app running utilizing **express** framework.

I installed the package using the command **npm install express --save** in the folder **nodejs-mobile/deps/npm/**.  I checked the **package.json** file and the folder **nodejs-mobile/deps/npm/node_modules/**, and there were references of express package.

After this installation, I made libs following the guidelines https://github.com/janeasystems/nodejs-mobile

Libs are good. I tested it with the **http** module, and I have no issues. 

But then I tried 

> var express = require('express');
> var app = express();
> app.get('/', function (req, res) {
>   res.send('Hello World');
> });
> app.listen(3000);

With this simple code, app started to crash.

I am wondering about the steps that I used to have **express** package available to app were right?

Appreciate your guidance.

**Comment by DeepakArora76** [comment]
By the way, Android is my test platform.

**Comment by DeepakArora76** [comment]
I see that the file **nodejs-mobile/deps/npm/package.json** contains **bundleDependencies** section, which does not contain the **express** module. Maybe by adding a reference to it in this section solves the problem. Making another lib, and see whether this change has any effect or not.

**Still crahes!**

**Comment by DeepakArora76** [comment]
Appreciate valuable tips to solve this issue.

**Comment by DeepakArora76** [comment]
How to bundle pure JS NPM Module like Express in Shared Object Library?

**Comment by jaimecbernardo** [comment]
Hi @DeepakArora76 , thank you for the issue.

For using node modules in node, it's advised to add a nodejs-project folder to your project, including a package.json, so that it looks similarly to a node project in the Desktop. Then you can run `npm install` inside and the node_modules folder containing your dependencies will be created there. At runtime, you'll then start node by passing the script path as an argument instead of the actual script contents. This is how it's working in the [`nodejs-mobile-react-native`](https://github.com/janeasystems/nodejs-mobile-react-native) and [`nodejs-mobile-cordova`](https://github.com/janeasystems/nodejs-mobile-cordova) plugins.

Android requires some additional steps. This quote is from an answer on [a similar issue specific to Android](https://github.com/janeasystems/nodejs-mobile/issues/44#issuecomment-363110177) :
>The main problem with Android is that the APK is essentially an archive file while the node runtime expects to be run on an environment with actual paths.
In terms of strategies to get around this, the `nodejs-mobile-cordova` and `nodejs-mobile-react-native` plugins expect the node code and modules to be on a project folder, added to the App's assets, which is copied to the App's document folder at runtime.
This code can be checked on either plugin: https://github.com/janeasystems/nodejs-mobile-react-native/blob/d478d029d76e7d1de8b52d1cd5c51f7d61067b31/android/src/main/java/com/janeasystems/rn_nodejs_mobile/RNNodeJsMobileModule.java for `react-native` or https://github.com/janeasystems/nodejs-mobile-cordova/blob/4fe04f39f731cf74139749b8675b2f68ba7d6642/src/android/java/com/janeasystems/cdvnodejsmobile/NodeJS.java for `cordova`.
The current version of this strategy first creates lists with the folder and file structure at build time so the copy is faster later on: https://github.com/janeasystems/nodejs-mobile-react-native/blob/d478d029d76e7d1de8b52d1cd5c51f7d61067b31/android/build.gradle#L60-L85 for `react-native` or https://github.com/janeasystems/nodejs-mobile-cordova/blob/4fe04f39f731cf74139749b8675b2f68ba7d6642/install/hooks/android/before-build.js for `cordova`.
There may be other strategies for this, depending on your application's requirements.

`npm` is in the source, since it is included in the releases of upstream Node.js as the default module downloader, but it's not included inside the `nodejs-mobile` library.

Regarding bundling npm modules in the library, it will be answered in the other issue that was opened about it: https://github.com/janeasystems/nodejs-mobile/issues/50

I hope this was helpful.

**Comment by DeepakArora76** [comment]
@jaimecbernardo: Many thanks for your prompt reply and valuable inputs. I managed to solve the problem with the tips from you. I hope it would be simple (not as complicated as for Android) for iOS platform. I will try to make a lib using the sample code from React-native/Cordova for iOS platform. This approach of using external/internal node-js modules have many advantages than embedding in Shared Object #50.

The experience that I gained in an attempt to solve the #50 will be mentioned in the report later today.

**Comment by jaimecbernardo** [comment]
Thank you for the feedback.

Yes, @DeepakArora76 , for iOS it's simpler, because iOS provides an actual sandboxed path to access the insides of the Application's package. If you add the `nodejs-project` as a Resource folder to the XCode project, you can start from inside the sandbox path. This is the react-native part: https://github.com/janeasystems/nodejs-mobile-react-native/blob/d478d029d76e7d1de8b52d1cd5c51f7d61067b31/ios/RNNodeJsMobile.m#L63-L69 and this is the cordova part: https://github.com/janeasystems/nodejs-mobile-cordova/blob/4fe04f39f731cf74139749b8675b2f68ba7d6642/src/ios/CDVNodeJS.mm#L132-L148

**Comment by saberprashant** [comment]
Hi @DeepakArora76 , how did you manage to make the Express server run with you app. I mean, I am almost doing the same which you did, that is, starting a server on port-5000 and accepting requests on ```/users```, but my server isn't working. I get 404 error whenever I send a request using POSTMAN.  (And my app is building perfectly, even the rn-bridge is working but server isn't working)
My code in `main.js` is:  

```
// Rename this sample file to main.js to use on your project.
// The main.js file will be overwritten in updates/reinstalls.

var rn_bridge = require('rn-bridge');
var express = require('express');

var app = express();

// Our first route
app.get('/users', function (req, res) {
  res.send('Hello Dev!');
  rn_bridge.channel.send("heya");
  // rn_bridge.channel.post('message', 'Hi there');
});

// Echo every message received from react-native.
rn_bridge.channel.on('message', (msg) => {
  rn_bridge.channel.send(msg);
} );

// Listen to port 5000
app.listen(5000, function () {
  console.log('Dev app listening on port 5000!');
});
```

Please help :)
