### ISSUE TITLE
 How to bundle pure JS NPM Module like Express in Shared Object Library?

### ISSUE THREAD

**Issue by DeepakArora76** [janeasystems/nodejs-mobile#50]

**Comment by jaimecbernardo** [comment]
Hi @DeepakArora76 , thank you for the question.

We haven't had the need to bundle npm modules inside the `nodejs-mobile` binaries yet.
If you'd like to give it a try, I'd recommend by starting to look at the build process that adds the builtin javascript files into a C file. The files are listed here: https://github.com/janeasystems/nodejs-mobile/blob/12747ef24b8cdad82b4dd5f9120386e012920243/node.gyp#L25-L141 and they seem to be converted here: https://github.com/janeasystems/nodejs-mobile/blob/12747ef24b8cdad82b4dd5f9120386e012920243/node.gyp#L449-L481

Let us know if you decide to give it a try and what results you end up having.
I hope this was helpful.

**Comment by DeepakArora76** [comment]
Hi @jaimecbernardo.

Thanks for your inputs.

I made a couple of quick attempts to see whether its possible by having Express module aligned to the `nodejs-mobile/lib/` directory structure and `nodejs-mobile/node.gyp` build configuration, but the outcomes were bleak. 

Express module is dependent on many other modules, and those dependent modules are dependent on others, this chain of dependencies makes it hard to build a correct `nodejs-mobile/lib/` directory structure.  

I started off with creating a new directory, followed by `npm init` and `npm install express --save`. This resulted in Express module in my directory under the folder `node_modules`

I copied and pasted the folder `node_modules` in `nodejs-mobile/lib/` , adjusted  `nodejs-mobile/node.gyp`, and started a build process. When an attempt is made to test `var express = require('express')`, a hard-coded script in the lib, the app started to crash, though  `require('http') ` was fine and other Http module APIs were found working.

I made another attempt where I copied the `index.js ` under the  `\node_modules\express` to `nodejs-mobile/lib/` and renamed to `express.js`. This also failed. 

I found these chain of dependent modules have `index.js` under their own directory, which I believe Node Js works this way to locate the modules. I renamed them to match the name of the module.

I tried many combinations like this, but all of them were unsuccessful.

A question comes, what will I gain having with the approach of bundling modules in the lib? Probably, scripts will execute fast? But this approach makes it difficult to upgrade or add new modules, as it requires to produce new lib again.

If you have some tips, I will attempt it again, otherwise, I will not be spending time on it for now.

**Comment by jaimecbernardo** [comment]
Hi, @DeepakArora76 

Thank you for sharing your experience.
The recommended approach to using native modules is to use a `nodejs-project` with a `package.json` inside, where you can run `npm install` as mentioned in https://github.com/janeasystems/nodejs-mobile/issues/49#issuecomment-367270153

Embedding modules in the `node_mobile` library binary is not a supported scenario and it's not been tested yet, so I don't remember of any additional tips that could be useful.

Regarding the specific issue of using express in Node.js, I trust it has already been solved in https://github.com/janeasystems/nodejs-mobile/issues/49 .

I'm closing this issue, as well, since it is a not support scenario.
Thank you for the details of your experiments, once again, as they'll be helpful to point to if the requirement of embedding node modules comes up.

**Comment by DeepakArora76** [comment]
Indeed, when the need arises, I will dive into it.
