### ISSUE TITLE
Running npm at runtime (not supported)

### ISSUE THREAD

**Issue by quinton-ashley** [JaneaSystems/nodejs-mobile#7]
I appreciate the amount of work that has already gone into this project and it is very exciting to even see a basic node.js server running on my iPhone and being able to open up a web browser on the phone and connect to it, absolutely mind blowing.  However I was wondering if there are plans to implement npm in the future?  It would be great to make an iOS app that could auto-update changes to it's npm modules just like on desktop, without having to recompile and ship updates to Apple's app store.

**Comment by tommyZZM** [comment]
i think Apple's  app store would not allow dynamic download running codes such as npm modules like the `jsPatch` before

but may be we can bundle npm modules staticly inside the application?

**Comment by mohlsen** [comment]
As long as it is code that is run by the interpreter (web content), it should be ok.  Certainly native node modules could not be used, but pure javascript modules could be downloaded and then used by the node process.

Other projects do this today, such as Microsoft's [CodePush](http://microsoft.github.io/code-push).  I don't see how this would be any different.

**Comment by jaimecbernardo** [comment]
Hi, @quinton-ashley
Thanks for the issue.

Currently, you can include pure javascript npm modules easily. In our react-native and cordova node projects by simply running npm install --save <module> inside the `nodejs-project` folder containing a `package.json`. It will create a `node_modules` path inside that will get embedded within the application and accessible by the Node.js runtime. You can also include modules in native apps, but some additional steps are needed so they are bundled with your application.

Native modules can also be included though support for that is still work in progress. Right now some manual steps are required to link them with your application. Also, not all existing native modules might compile for mobile OSes and may require non-trivial adaptations.

Regarding live updating the app with npm, I think that's beyond the scope of the project in that it's a feature, while useful, that is not specifically needed for mobile as opposed to desktop/server Node. See the [project goals](https://github.com/janeasystems/nodejs-mobile#project-goals).

Having said that, any user-land solution that works for regular node should also work here, with a couple of caveats:
1) It would work for JS modules, but not for native modules, until we implement a way to load them dynamically.
2) I am not sure if Apple would allow that, since [it is only allowed if it's on WebKit](https://developer.apple.com/programs/ios/information/iOS_Program_Information_4_3_15.pdf):
> 3.3.2 An Application may not download or install executable code. Interpreted
code may only be used in an Application if all scripts, code and interpreters are
packaged in the Application and not downloaded. The only exception to the
foregoing is scripts and code downloaded and run by Apple's built-in WebKit
framework or JavascriptCore, provided that such scripts and code do not change
the primary purpose of the Application by providing features or functionality that are
inconsistent with the intended and advertised purpose of the Application as
submitted to the App Store.

**Comment by mohlsen** [comment]
ah, @jaimecbernardo, thanks for the clarification.  That makes [my post](https://github.com/janeasystems/nodejs-mobile/issues/7#issuecomment-334437519) about it technically being possible not so much the case.  You can use something like CodePush for web content being rendered by the WebView (such as app content for a Cordova app), but not something executed by another interpreter like this project is using.

**Comment by wspl** [comment]
You can also compile your node.js project with webpack and running with single distributed application bundled file.

**Comment by bil-ash** [comment]
Using npm commands in cordova android plugin quits the app, any workarounds?
As a matter of fact it would be better if there is also an option of installimg npm while installing the plugin

**Comment by jaimecbernardo** [comment]
Hi @bil-ash, thank you for the question.

Are you trying to run npm in actual devices? That's not a supported scenario, currently, as it would be against Apple's App guidlines, as described in this earlier comment: https://github.com/janeasystems/nodejs-mobile/issues/7#issuecomment-334439498

Needed npm dependencies should be installed and included in the application's project folder before building the App.

I hope this was helpful.

**Comment by bil-ash** [comment]
Actually I need to use the grpc module,which involves native code and whose installation is best done using npm.Any suggestion for implementation?
I am building for android on windows.

**Comment by jaimecbernardo** [comment]
Hi @bil-ash,
We are currently working on a way to make npm cross-compile for nodejs-mobile on your dev machine.
Essentially you'd have to try and trick npm into compiling the native module using the Android NDK and nodejs-mobile headers.

This is also how node can be compiled for Android, by building a standalone toolchain and setting environment variables so gyp uses it: https://github.com/janeasystems/nodejs-mobile/blob/mobile-master/android-configure

Native modules essentially build a `.node` file that is a shared library to be loaded by node at runtime.
I've run a quick test using the method we're developing and `grpc` can be built for android on macOS but you have to remove this line https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/binding.gyp#L931 since `-zdefs` seems to be an invalid flag for the NDK. I haven't tried running it, however, because I couldn't find any readily available sample code.

We hope to release an experimental native modules support soon, but cross compiling for Android using Windows won't be there initially.

I hope this was helpful.

**Comment by bil-ash** [comment]
May be this issue can be closed.
Now whatever remains to be resolved can be done in issue #4.

**Comment by jaimecbernardo** [comment]
Hi @bil-ash , thank you.
This issue is related to bringing npm support to the runtime of `nodejs-mobile`, while https://github.com/janeasystems/nodejs-mobile/issues/4 is specific to native modules.

I've added the question label, as this is more of a question/discussion issue and I think it's helpful for it to stay open.

**Comment by quinton-ashley** [comment]
I'm confused, so is there support for npm on Android now but not iOS?

**Comment by jaimecbernardo** [comment]
Hi @quinton-ashley .
There is no support for running npm at runtime on the devices. While it could be possible to do it, it would be forbidden by iOS App Store Guidelines.

Every npm module needed should be packaged with the Application at build time. That is supported for both platforms in the plugins.

I hope this is helpful.

**Comment by quinton-ashley** [comment]
oh okay thank you

**Comment by jaimecbernardo** [comment]
Since this issue is causing confusion, I've changed the title and will close it, since it refers to a not supported feature.

**Comment by bil-ash** [comment]
https://play.google.com/store/apps/details?id=io.tempage.dorynode
The android app to which the above link refers uses npm at runtime and does it very well. So it basically means that android allows npm at runtime.

**Comment by bil-ash** [comment]
The approach taken by the app is a bit different,it use node dependencies as shared objects and node as an executable. Just a simple extraction of the apk revealed these details. It means google is very lenient in terms of executable and nodejs-mobile can provide npm support on android at some point in the future. So may be the issue needs to be reopened.

**Comment by jaimecbernardo** [comment]
Thank you for the reference!

The issue was closed for the confusion it may cause, since we expect the supported scenario to be having the modules pre-packaged in the Application.

It's possible that npm can be run already if it's possible to call it as if it was a module as long as you include it. Let us know if you decide to give it a try so we can know the results.

On other hand, even if npm comes as the default packager in the node installations for desktop, I think it's a separate component and not really part of node. It should still be possible to include npm alongside node in your application if it runs on Android. Since we're trying to keep feature parity between platforms, it's a component we're not planning on supporting right now. Of course that may change if there's a strong demand for it.

I hope this was helpful.

The issue may be reopened in the future. Discussion can be still had here, of course.

**Comment by jaimecbernardo** [comment]
Reopening the issue, so it can be found more easily.

**Comment by diogoviannaaraujo** [comment]
About apple guidelines, how would this differ from expo strategy?

I was wondering if I could use react native and Nodejs-mobile-react-native to Clone, run and edit some simple web servers on a iPad.

Even if iOS App Store don’t aprove it, it would be nice for local use and sideloading

**Comment by jaimecbernardo** [comment]
Hi @diogoviannaaraujo ,

Not sure what you mean by expo strategy.

Regarding your usage scenario, the nodejs-mobile instance is supposed to keep running, so it depends if your strategy for achieving this would need to restart the nodejs-mobile loop or not, since that's not a supported scenario. So, you'd probably need to do a native application with the library and wire it differently to support your needs on iOS, since the application package, where the nodejs-project is loaded from in the react native plugin, is not writable.

While editing the server in an iPad is not supported, having the server developed in a Desktop machine and then included in the App for testing in the device is a scenario that works.

**Comment by diogoviannaaraujo** [comment]
I was refereeing to Expo app downloading code to run. Was wondering how different downloading some js modules would be from that.

I was hoping to download some js files to the internal file system using a react native app or even maybe a native app and then spawn a node instance to execute that code.

**Comment by jaimecbernardo** [comment]
Hi @diogoviannaaraujo , It should be possible to download the project files to the application's user files folder and starting the node instance there. Spawning new instances would likely not work, though: https://code.janeasystems.com/nodejs-mobile/faq#can-i-run-two-or-more-nodejs-instances
For this, a native app would be the way to go, since the plugins currently start the project from an read-only path on iOS.
