### ISSUE TITLE
Type error when running nodejs-mobile-react-native on android

### ISSUE THREAD

**Issue by n3qit** [janeasystems/nodejs-mobile#85]
As a base I use (https://github.com/react-community/create-react-native-app/issues). Over put everything like in readme in usage (https://github.com/janeasystems/nodejs-mobile-react-native). When running on the emulator, I get the following:

```
18:07:31: Finished building JavaScript bundle in 14ms
18:07:32: Running app on Android SDK built for x86 in development mode

18:07:35: TypeError: undefined is not an object (evaluating 'RNNodeJsMobile.startNodeProject')

This error is located at:
    in App (at registerRootComponent.js:35)
    in RootErrorBoundary (at registerRootComponent.js:34)
    in ExpoRootComponent (at renderApplication.js:33)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:32)
- node_modules/nodejs-mobile-react-native/index.js:17:17 in start
* App.js:9:19 in componentWillMount
- node_modules/react-proxy/modules/createPrototypeProxy.js:44:35 in proxiedMethod
- node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:6698:6 in callComponentWillMount
- ... 24 more stack frames from framework internals
```

My function in trace:

```
componentWillMount()
    {
      nodejs.start("main.js");
      nodejs.channel.addListener(
        "message",
        (msg) => {
          alert("From node: " + msg);
        },
        this
      );
    }
```

What am i doing wrong?

* **Node Version**: v8.1.0
* **Platform**: 16.04.1-Ubuntu

**Comment by jaimecbernardo** [comment]
Hi @Lonny95 ,
Not familiar with `create-react-native-app`, but it sounds like it won't work with `nodejs-mobile-react-native`, due to [this limitation specified in the README.md](https://github.com/react-community/create-react-native-app/tree/1808872a1f5b69d09ed977a9a04ae689427df095#what-are-the-limitations-of-create-react-native-app):
> The main limitation of a Create React Native App project is that it must be written in pure JavaScript and not have any dependencies which rely on custom native code (i.e. ones which require running react-native link to work).

The `nodejs-mobile-react-native` plugin has native code, so it requires running `react-native link`, as [specified in the instructions](https://github.com/janeasystems/nodejs-mobile-react-native/tree/05e1748831bca8b8f053dcf80a348f3dc782596c#installation).

My advice would be to follow the instructions in the official [Getting Started](https://facebook.github.io/react-native/docs/getting-started.html), under "Building Projects with Native Code".

**Comment by n3qit** [comment]
Oh, thank you! 
By the way, is there any possibilities to implement https://github.com/libp2p/js-libp2p in app to bouth IOS and android platforms without using native code? 
p.s. I tried cardova, but it doesn't support raw node modules

**Comment by jaimecbernardo** [comment]
Hi @Lonny95 ,
I'm not familiar with that module. It mentions having a browser version as well: https://github.com/libp2p/js-libp2p#bundles

A node runtime needs to execute in a native code environment, since its code base has C++ and it accesses Operating System APIs.

p.s. There is a cordova plugin with `nodejs-mobile` as well: https://www.npmjs.com/package/nodejs-mobile-cordova

**Comment by n3qit** [comment]
Thank you again, you r the best!

**Comment by jgtoriginal** [comment]
For anybody getting this issue.
Following the `create-react-native-app` guide will create an expo project for you, which doesn't allow to integrate with native components (such as `nodejs-mobile-react-native` which requires `react-native link` to work).
So, the way to fix this is to divert from expo and creating a `Plain` React Native app. You do this by `npm eject`, which is further down on the same `create-react-native-app` guide.
Once you did that, you will be able to follow the steps provided on the [`nodejs-mobile-react-native`](https://code.janeasystems.com/nodejs-mobile/getting-started-react-native) and get your nodejs instance running.

**Comment by cmosboss** [comment]
@jgtoriginal So this is very helpful information, does this mean that you cannot use expo and this package at the same time? That appears to be the case. When I am ejecting I have options to either use a regular react native app, or a react native app with expo sdk, if I chose the SDK I still get this issue. Otherwise I can make it plain but I have no expo features. Is there any work around to this?
