### ISSUE TITLE
Old Engines

### ISSUE THREAD

**Issue by ohenepee** [janeasystems/nodejs-mobile#93]
Hello, thanks for this great library... however I couldn't help but notice that almost all the engines used were pretty old in the latest **nodejs-mobile 0.1.6**:
```
"node" : "8.6.0" --> Latest LTS (8.11.3) & Latest Current (10.6.0)
"chakracore" : "1.7.1.0" --> Latest (1.10.x)
```

Could there be any specific reason for using these old releases when faster and _ES6/7/8-feature-packed_ releases exist?

**Comment by jaimecbernardo** [comment]
Hi @ohenepee ,

Thank you for the feedback.

**nodejs-mobile**  is a fork of **node-chakracore**, for which the latest version was *8.6.0* until earlier this year. We've been keeping on that version since it's been stable while working on other features for mobile, such as being able to run the unit tests on mobile devices, more useful APIs for the plugins and the recent native modules support.

We do plan on updating the node version to latest LTS of **node-chakracore**, but the project's effort has been on adding features useful for mobile / missing features for the plugins, for which keeping a stable version of the core library has been useful.

I hope this answered your question.

**Comment by ohenepee** [comment]
Yes its very understandable
